### PR TITLE
Add API scaffold to the project

### PR DESCRIPTION
**Pull request by duksis**
* [x] New Phoenix app
* [x] Add Absinthe GraphQL
* [x] Development setup with docker compose
~* [ ] CI setup~
~* [ ] Building of production image~
~* [ ] Deployment~

### CODE REVIEW

**Comment by slashmili** [comment]
@duksis are we going to use github Action for CI?

**Comment by duksis** [comment]
@slashmili would be my preferred choice here - main reason being that it looks like a decent tool and I want to try it out.
But I'm also up for anything else.

**Comment by slashmili** [comment]
@duksis I wanted to suggest to use GithubAction as well.

BTW maybe the docker-compose should go to the root directory.

**Comment by duksis** [comment]
@slashmili I'll create separate PR's for the remaining points

**Pull request merged**
